### ISSUE TITLE
path to fa2cmap_multi.pl

### ISSUE THREAD

**Issue by JennyHTLee** [ucrbioinfo/Novo_Stitch#1]
Hi,

I executed main.py in my working dir this way 
"python /home/user/programs/Novo_Stitch/scripts/main.py"

But it cannot find my fa2cmap_multi.pl, I get:
 "Can't open perl script "./tools/fa2cmap_multi.pl": No such file or directory" 

It works after I edited lines 35-37 of stitch.py to full paths:
    DIGEST = "/home/user/programs/Novo_stitch/tools/fa2cmap_multi.pl"
    CPP_1 = "/home/user/programs/Novo_stitch/tools/Script_mapping_contigs2contigs"
    CPP_2 = "/home/user/programs/Novo_stitch/tools/Script_mapping_contigs2stitched_contigs"

Cheers,
Jenny

**Comment by pwhhero** [comment]
Hi Jenny, 
As said in readme file, for current version of Novo&Stitch, the users have to go to "Novo_Stitch" folder first, and then execute main.py using "$python ./scripts/main.py". Because only in "Novo_Stitch" folder,  "./tools/fa2cmap_multi.pl" could be found. 
Sorry for this inconvenience. We will improve our program as soon as possible to support other ways to use. 

Best, 
Weihua

**Comment by pwhhero** [comment]
Thanks very much for telling us this issue!

Weihua

**Comment by JennyHTLee** [comment]
Ah I must have missed that line in the readme, thanks!

Cheers,
Jenny
